# Generated by Django 2.0.6 on 2019-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFitnessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=200)),
                ('calories', models.IntegerField(default=0)),
                ('date', models.DateField(default='')),
            ],
        ),
    ]
